name: movies
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  flutter_redux: ^0.9.0
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.7.0
  redux_epics: ^0.15.1
  redux: ^5.0.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
  flutter_lints: ^1.0.0

dependency_overrides:
    analyzer: ^3.0.0


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  